//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// Nombre de archivo original:
// Fecha de generación: 27/11/2019 21:51:17
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// No hay comentarios para NorthwindData en el esquema.
    /// </summary>
    public partial class NorthwindData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Inicializar un nuevo objeto NorthwindData.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NorthwindData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Como el espacio de nombres configurado para la referencia de este servicio
        /// en Visual Studio es diferente al indicado en el 
        /// esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Como el espacio de nombres configurado para la referencia de este servicio
        /// en Visual Studio es diferente al indicado en el 
        /// esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// No hay comentarios para Categories en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CategoriesItem> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<CategoriesItem>("Categories");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CategoriesItem> _Categories;
        /// <summary>
        /// No hay comentarios para Product_Sales_for_1997 en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product_Sales_for_1997Item> Product_Sales_for_1997
        {
            get
            {
                if ((this._Product_Sales_for_1997 == null))
                {
                    this._Product_Sales_for_1997 = base.CreateQuery<Product_Sales_for_1997Item>("Product_Sales_for_1997");
                }
                return this._Product_Sales_for_1997;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product_Sales_for_1997Item> _Product_Sales_for_1997;
        /// <summary>
        /// No hay comentarios para Products en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ProductsItem> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<ProductsItem>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ProductsItem> _Products;
        /// <summary>
        /// No hay comentarios para Categories en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCategories(CategoriesItem categoriesItem)
        {
            base.AddObject("Categories", categoriesItem);
        }
        /// <summary>
        /// No hay comentarios para Product_Sales_for_1997 en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProduct_Sales_for_1997(Product_Sales_for_1997Item product_Sales_for_1997Item)
        {
            base.AddObject("Product_Sales_for_1997", product_Sales_for_1997Item);
        }
        /// <summary>
        /// No hay comentarios para Products en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(ProductsItem productsItem)
        {
            base.AddObject("Products", productsItem);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"CategoriesItem\"><Key><PropertyRef Name=\"Catego" +
                "ryID\" /></Key><Property Name=\"CategoryID\" Type=\"Edm.Int32\" Nullable=\"false\" anno" +
                "tation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"CategoryName\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" MaxLength=\"15\" ConcurrencyMode=\"Fixed\" /><Property Na" +
                "me=\"Description\" Type=\"Edm.String\" MaxLength=\"Max\" /><Property Name=\"Picture\" Ty" +
                "pe=\"Edm.Binary\" MaxLength=\"Max\" /><NavigationProperty Name=\"Products\" Relationsh" +
                "ip=\"LightSwitchApplication.FK_Products_Categories\" ToRole=\"Products\" FromRole=\"C" +
                "ategories\" /></EntityType><EntityType Name=\"Product_Sales_for_1997Item\"><Key><Pr" +
                "opertyRef Name=\"CategoryName\" /><PropertyRef Name=\"ProductName\" /></Key><Propert" +
                "y Name=\"CategoryName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"15\" /><Prope" +
                "rty Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" /><Prop" +
                "erty Name=\"ProductSales\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" Concurrency" +
                "Mode=\"Fixed\" /></EntityType><EntityType Name=\"ProductsItem\"><Key><PropertyRef Na" +
                "me=\"ProductID\" /></Key><Property Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"ProductName\" T" +
                "ype=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" ConcurrencyMode=\"Fixed\" /><Prop" +
                "erty Name=\"SupplierID\" Type=\"Edm.Int32\" ConcurrencyMode=\"Fixed\" /><Property Name" +
                "=\"QuantityPerUnit\" Type=\"Edm.String\" MaxLength=\"20\" ConcurrencyMode=\"Fixed\" /><P" +
                "roperty Name=\"UnitPrice\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" Concurrency" +
                "Mode=\"Fixed\" /><Property Name=\"UnitsInStock\" Type=\"Edm.Int16\" ConcurrencyMode=\"F" +
                "ixed\" /><Property Name=\"UnitsOnOrder\" Type=\"Edm.Int16\" ConcurrencyMode=\"Fixed\" /" +
                "><Property Name=\"ReorderLevel\" Type=\"Edm.Int16\" ConcurrencyMode=\"Fixed\" /><Prope" +
                "rty Name=\"Discontinued\" Type=\"Edm.Boolean\" Nullable=\"false\" ConcurrencyMode=\"Fix" +
                "ed\" /><Property Name=\"CategoryID\" Type=\"Edm.Int32\" ConcurrencyMode=\"Fixed\" /><Na" +
                "vigationProperty Name=\"CategoriesItem\" Relationship=\"LightSwitchApplication.FK_P" +
                "roducts_Categories\" ToRole=\"Categories\" FromRole=\"Products\" /></EntityType><Asso" +
                "ciation Name=\"FK_Products_Categories\"><End Role=\"Categories\" Type=\"LightSwitchAp" +
                "plication.CategoriesItem\" Multiplicity=\"0..1\" /><End Role=\"Products\" Type=\"Light" +
                "SwitchApplication.ProductsItem\" Multiplicity=\"*\" /><ReferentialConstraint><Princ" +
                "ipal Role=\"Categories\"><PropertyRef Name=\"CategoryID\" /></Principal><Dependent R" +
                "ole=\"Products\"><PropertyRef Name=\"CategoryID\" /></Dependent></ReferentialConstra" +
                "int></Association><EntityContainer Name=\"NorthwindData\" m:IsDefaultEntityContain" +
                "er=\"true\"><EntitySet Name=\"Categories\" EntityType=\"LightSwitchApplication.Catego" +
                "riesItem\" /><EntitySet Name=\"Product_Sales_for_1997\" EntityType=\"LightSwitchAppl" +
                "ication.Product_Sales_for_1997Item\" /><EntitySet Name=\"Products\" EntityType=\"Lig" +
                "htSwitchApplication.ProductsItem\" /><AssociationSet Name=\"FK_Products_Categories" +
                "\" Association=\"LightSwitchApplication.FK_Products_Categories\"><End Role=\"Categor" +
                "ies\" EntitySet=\"Categories\" /><End Role=\"Products\" EntitySet=\"Products\" /></Asso" +
                "ciationSet><FunctionImport Name=\"Microsoft_LightSwitch_GetCanInformation\" Return" +
                "Type=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"dataServiceMembers\" Type=\"" +
                "Edm.String\" Mode=\"In\" /></FunctionImport></EntityContainer></Schema></edmx:DataS" +
                "ervices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.CategoriesItem en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Categories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CategoryID")]
    public partial class CategoriesItem : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto CategoriesItem.
        /// </summary>
        /// <param name="categoryID">Valor inicial de CategoryID.</param>
        /// <param name="categoryName">Valor inicial de CategoryName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CategoriesItem CreateCategoriesItem(int categoryID, string categoryName)
        {
            CategoriesItem categoriesItem = new CategoriesItem();
            categoriesItem.CategoryID = categoryID;
            categoriesItem.CategoryName = categoryName;
            return categoriesItem;
        }
        /// <summary>
        /// No hay comentarios para la propiedad CategoryID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                if (object.Equals(this.CategoryID, value))
                {
                    return;
                }
                this._CategoryID = value;
                this.OnCategoryIDChanged();
                this.OnPropertyChanged("CategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad CategoryName en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                if (object.Equals(this.CategoryName, value))
                {
                    return;
                }
                this._CategoryName = value;
                this.OnCategoryNameChanged();
                this.OnPropertyChanged("CategoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Description en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                if (object.Equals(this.Description, value))
                {
                    return;
                }
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Picture en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Picture
        {
            get
            {
                if ((this._Picture != null))
                {
                    return ((byte[])(this._Picture.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPictureChanging(value);
                if (object.Equals(this.Picture, value))
                {
                    return;
                }
                this._Picture = value;
                this.OnPictureChanged();
                this.OnPropertyChanged("Picture");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Picture;
        partial void OnPictureChanging(byte[] value);
        partial void OnPictureChanged();
        /// <summary>
        /// No hay comentarios para Products en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ProductsItem> Products
        {
            get
            {
                this.@__Products.EnsureValueInitialized();
                return this._Products;
            }
            set
            {
                this._Products = value;
                this.OnPropertyChanged("Products");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ProductsItem> _Products = new global::System.Data.Services.Client.DataServiceCollection<ProductsItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.Product_Sales_for_1997Item en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryName
    /// ProductName
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Product_Sales_for_1997")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CategoryName", "ProductName")]
    public partial class Product_Sales_for_1997Item : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Product_Sales_for_1997Item.
        /// </summary>
        /// <param name="categoryName">Valor inicial de CategoryName.</param>
        /// <param name="productName">Valor inicial de ProductName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product_Sales_for_1997Item CreateProduct_Sales_for_1997Item(string categoryName, string productName)
        {
            Product_Sales_for_1997Item product_Sales_for_1997Item = new Product_Sales_for_1997Item();
            product_Sales_for_1997Item.CategoryName = categoryName;
            product_Sales_for_1997Item.ProductName = productName;
            return product_Sales_for_1997Item;
        }
        /// <summary>
        /// No hay comentarios para la propiedad CategoryName en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                if (object.Equals(this.CategoryName, value))
                {
                    return;
                }
                this._CategoryName = value;
                this.OnCategoryNameChanged();
                this.OnPropertyChanged("CategoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// No hay comentarios para la propiedad ProductName en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                if (object.Equals(this.ProductName, value))
                {
                    return;
                }
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// No hay comentarios para la propiedad ProductSales en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> ProductSales
        {
            get
            {
                return this._ProductSales;
            }
            set
            {
                this.OnProductSalesChanging(value);
                if (object.Equals(this.ProductSales, value))
                {
                    return;
                }
                this._ProductSales = value;
                this.OnProductSalesChanged();
                this.OnPropertyChanged("ProductSales");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _ProductSales;
        partial void OnProductSalesChanging(global::System.Nullable<decimal> value);
        partial void OnProductSalesChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para LightSwitchApplication.ProductsItem en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Products")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductID")]
    public partial class ProductsItem : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto ProductsItem.
        /// </summary>
        /// <param name="productID">Valor inicial de ProductID.</param>
        /// <param name="productName">Valor inicial de ProductName.</param>
        /// <param name="discontinued">Valor inicial de Discontinued.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ProductsItem CreateProductsItem(int productID, string productName, bool discontinued)
        {
            ProductsItem productsItem = new ProductsItem();
            productsItem.ProductID = productID;
            productsItem.ProductName = productName;
            productsItem.Discontinued = discontinued;
            return productsItem;
        }
        /// <summary>
        /// No hay comentarios para la propiedad ProductID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                if (object.Equals(this.ProductID, value))
                {
                    return;
                }
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad ProductName en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                if (object.Equals(this.ProductName, value))
                {
                    return;
                }
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// No hay comentarios para la propiedad SupplierID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this.OnSupplierIDChanging(value);
                if (object.Equals(this.SupplierID, value))
                {
                    return;
                }
                this._SupplierID = value;
                this.OnSupplierIDChanged();
                this.OnPropertyChanged("SupplierID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _SupplierID;
        partial void OnSupplierIDChanging(global::System.Nullable<int> value);
        partial void OnSupplierIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad QuantityPerUnit en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QuantityPerUnit
        {
            get
            {
                return this._QuantityPerUnit;
            }
            set
            {
                this.OnQuantityPerUnitChanging(value);
                if (object.Equals(this.QuantityPerUnit, value))
                {
                    return;
                }
                this._QuantityPerUnit = value;
                this.OnQuantityPerUnitChanged();
                this.OnPropertyChanged("QuantityPerUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QuantityPerUnit;
        partial void OnQuantityPerUnitChanging(string value);
        partial void OnQuantityPerUnitChanged();
        /// <summary>
        /// No hay comentarios para la propiedad UnitPrice en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                if (object.Equals(this.UnitPrice, value))
                {
                    return;
                }
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
                this.OnPropertyChanged("UnitPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Nullable<decimal> value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// No hay comentarios para la propiedad UnitsInStock en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> UnitsInStock
        {
            get
            {
                return this._UnitsInStock;
            }
            set
            {
                this.OnUnitsInStockChanging(value);
                if (object.Equals(this.UnitsInStock, value))
                {
                    return;
                }
                this._UnitsInStock = value;
                this.OnUnitsInStockChanged();
                this.OnPropertyChanged("UnitsInStock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _UnitsInStock;
        partial void OnUnitsInStockChanging(global::System.Nullable<short> value);
        partial void OnUnitsInStockChanged();
        /// <summary>
        /// No hay comentarios para la propiedad UnitsOnOrder en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> UnitsOnOrder
        {
            get
            {
                return this._UnitsOnOrder;
            }
            set
            {
                this.OnUnitsOnOrderChanging(value);
                if (object.Equals(this.UnitsOnOrder, value))
                {
                    return;
                }
                this._UnitsOnOrder = value;
                this.OnUnitsOnOrderChanged();
                this.OnPropertyChanged("UnitsOnOrder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _UnitsOnOrder;
        partial void OnUnitsOnOrderChanging(global::System.Nullable<short> value);
        partial void OnUnitsOnOrderChanged();
        /// <summary>
        /// No hay comentarios para la propiedad ReorderLevel en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> ReorderLevel
        {
            get
            {
                return this._ReorderLevel;
            }
            set
            {
                this.OnReorderLevelChanging(value);
                if (object.Equals(this.ReorderLevel, value))
                {
                    return;
                }
                this._ReorderLevel = value;
                this.OnReorderLevelChanged();
                this.OnPropertyChanged("ReorderLevel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _ReorderLevel;
        partial void OnReorderLevelChanging(global::System.Nullable<short> value);
        partial void OnReorderLevelChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Discontinued en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Discontinued
        {
            get
            {
                return this._Discontinued;
            }
            set
            {
                this.OnDiscontinuedChanging(value);
                if (object.Equals(this.Discontinued, value))
                {
                    return;
                }
                this._Discontinued = value;
                this.OnDiscontinuedChanged();
                this.OnPropertyChanged("Discontinued");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Discontinued;
        partial void OnDiscontinuedChanging(bool value);
        partial void OnDiscontinuedChanged();
        /// <summary>
        /// No hay comentarios para la propiedad CategoryID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                if (object.Equals(this.CategoryID, value))
                {
                    return;
                }
                this._CategoryID = value;
                this.OnCategoryIDChanged();
                this.OnPropertyChanged("CategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CategoryID;
        partial void OnCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// No hay comentarios para CategoriesItem en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CategoriesItem CategoriesItem
        {
            get
            {
                this.@__CategoriesItem.EnsureValueInitialized();
                return this._CategoriesItem;
            }
            set
            {
                CategoriesItem previous = this.CategoriesItem;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._CategoriesItem = null;
                    this.@__CategoriesItem.OnValueSet();
                    previous.Products.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.CategoryID = value.CategoryID;
                    }
                    else
                    {
                        this.CategoryID = default(global::System.Nullable<int>);
                    }
                }
                this._CategoriesItem = value;
                this.@__CategoriesItem.OnValueSet();
                if ((value != null))
                {
                    value.@__Products.Add(this);
                }
                this.___OnPropertyChanged("CategoriesItem");
                this.OnPropertyChanged("CategoriesItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CategoriesItem _CategoriesItem;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
