//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Permite administrar la seguridad de la aplicación.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Grants permissions for adding new Employee entities
        /// </summary>
        public const string Can_Add_Employees = "LightSwitchApplication:Can_Add_Employees";
        /// <summary>
        /// Grants permissions for removing Employee entities
        /// </summary>
        public const string Can_Delete_Employees = "LightSwitchApplication:Can_Delete_Employees";
        /// <summary>
        /// Grants permissions for editing Employee entities
        /// </summary>
        public const string Can_Edit_Employees = "LightSwitchApplication:Can_Edit_Employees";
        /// <summary>
        /// Grants permissions for viewing Employee entities
        /// </summary>
        public const string Can_View_Employees = "LightSwitchApplication:Can_View_Employees";
        /// <summary>
        /// Grants permission to read customer information
        /// </summary>
        public const string Can_View_Customers = "LightSwitchApplication:Can_View_Customers";
        /// <summary>
        /// Grants permission to add a new Customer instance
        /// </summary>
        public const string Can_Add_Customers = "LightSwitchApplication:Can_Add_Customers";
        /// <summary>
        /// Grants permission to edit Customer information
        /// </summary>
        public const string Can_Edit_Customers = "LightSwitchApplication:Can_Edit_Customers";
        /// <summary>
        /// Grants permission for removing Customer entities
        /// </summary>
        public const string Can_Delete_Customers = "LightSwitchApplication:Can_Delete_Customers";
        /// <summary>
        /// Grants permission to read Order information
        /// </summary>
        public const string Can_View_Orders = "LightSwitchApplication:Can_View_Orders";
        /// <summary>
        /// Grants permission to add a new Order instance
        /// </summary>
        public const string Can_Add_Orders = "LightSwitchApplication:Can_Add_Orders";
        /// <summary>
        /// Grants permission to edit Order information
        /// </summary>
        public const string Can_Edit_Orders = "LightSwitchApplication:Can_Edit_Orders";
        /// <summary>
        /// Grants permission for removing Order entities
        /// </summary>
        public const string Can_Delete_Orders = "LightSwitchApplication:Can_Delete_Orders";
        /// <summary>
        /// Grants permission to read Order Details information
        /// </summary>
        public const string Can_View_OrderDetails = "LightSwitchApplication:Can_View_OrderDetails";
        /// <summary>
        /// Grants permission to add a new OrderDetail instance
        /// </summary>
        public const string Can_Add_OrderDetails = "LightSwitchApplication:Can_Add_OrderDetails";
        /// <summary>
        /// Grants permission to edit Order Detail information
        /// </summary>
        public const string Can_Edit_OrderDetails = "LightSwitchApplication:Can_Edit_OrderDetails";
        /// <summary>
        /// Grants permission for removing Order Detail entities
        /// </summary>
        public const string Can_Delete_OrderDetails = "LightSwitchApplication:Can_Delete_OrderDetails";
        /// <summary>
        /// Grants permission to read Product information
        /// </summary>
        public const string Can_View_Products = "LightSwitchApplication:Can_View_Products";
        /// <summary>
        /// Grants permission to add a new Product instance
        /// </summary>
        public const string Can_Add_Products = "LightSwitchApplication:Can_Add_Products";
        /// <summary>
        /// Grants permission to edit Product information
        /// </summary>
        public const string Can_Edit_Products = "LightSwitchApplication:Can_Edit_Products";
        /// <summary>
        /// Grants permission for removing Product entities
        /// </summary>
        public const string Can_Delete_Products = "LightSwitchApplication:Can_Delete_Products";
        /// <summary>
        /// Grants permission to read Invoice information
        /// </summary>
        public const string Can_View_Invoices = "LightSwitchApplication:Can_View_Invoices";
        /// <summary>
        /// Grants permission to add a new Invoice instance
        /// </summary>
        public const string Can_Add_Invoices = "LightSwitchApplication:Can_Add_Invoices";
        /// <summary>
        /// Grants permission to edit Invoice information
        /// </summary>
        public const string Can_Edit_Invoices = "LightSwitchApplication:Can_Edit_Invoices";
        /// <summary>
        /// Grants permission for removing Invoice entities
        /// </summary>
        public const string Can_Delete_Invoices = "LightSwitchApplication:Can_Delete_Invoices";

        /// <summary>
        /// Obtiene todos los permisos definidos para la aplicación. esto incluye los permisos del sistema y definidos por el usuario.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
