

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class Product_Sales_for_1997Item : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Product_Sales_for_1997Item.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Product_Sales_for_1997Item()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Product_Sales_for_1997Item(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Product_Sales_for_1997Item> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Sales_for_1997Item_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Sales_for_1997Item_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CategoryName
        {
            get
            {
                return global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.CategoryName);
            }
            set
            {
                global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.CategoryName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CategoryName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CategoryName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CategoryName_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProductName
        {
            get
            {
                return global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.ProductName);
            }
            set
            {
                global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.ProductName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductName_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> ProductSales
        {
            get
            {
                return global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.ProductSales);
            }
            set
            {
                global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.ProductSales, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductSales_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductSales_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductSales_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Product_Sales_for_1997Item,
                global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass,
                global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.IImplementation,
                global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.CategoryName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass>.Entry
                __Product_Sales_for_1997ItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass>.Entry(
                    global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.__Product_Sales_for_1997Item_CreateNew,
                    global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.__Product_Sales_for_1997Item_Created,
                    global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.__Product_Sales_for_1997Item_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Product_Sales_for_1997Item __Product_Sales_for_1997Item_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Product_Sales_for_1997Item> es)
            {
                return new global::LightSwitchApplication.Product_Sales_for_1997Item(es);
            }
            private static void __Product_Sales_for_1997Item_Created(global::LightSwitchApplication.Product_Sales_for_1997Item e)
            {
                e.Product_Sales_for_1997Item_Created();
            }
            private static bool __Product_Sales_for_1997Item_AllowSaveWithErrors(global::LightSwitchApplication.Product_Sales_for_1997Item e)
            {
                bool result = false;
                e.Product_Sales_for_1997Item_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string> CategoryName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.CategoryName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string> ProductName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.ProductName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::System.Nullable<decimal>> ProductSales
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties.ProductSales) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string CategoryName { get; set; }
                new string ProductName { get; set; }
                new global::System.Nullable<decimal> ProductSales { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Entry
                    CategoryName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Entry(
                        "CategoryName",
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._CategoryName_Stub,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._CategoryName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._CategoryName_Validate,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._CategoryName_GetImplementationValue,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._CategoryName_SetImplementationValue,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._CategoryName_OnValueChanged);
                private static void _CategoryName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d, object sf)
                {
                    c(d, ref d._CategoryName, sf);
                }
                private static bool _CategoryName_ComputeIsReadOnly(global::LightSwitchApplication.Product_Sales_for_1997Item e)
                {
                    bool result = false;
                    e.CategoryName_IsReadOnly(ref result);
                    return result;
                }
                private static void _CategoryName_Validate(global::LightSwitchApplication.Product_Sales_for_1997Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CategoryName_Validate(r);
                }
                private static string _CategoryName_GetImplementationValue(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d)
                {
                    return d.ImplementationEntity.CategoryName;
                }
                private static void _CategoryName_SetImplementationValue(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CategoryName = v;
                }
                private static void _CategoryName_OnValueChanged(global::LightSwitchApplication.Product_Sales_for_1997Item e)
                {
                    e.CategoryName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Entry
                    ProductName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Entry(
                        "ProductName",
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductName_Stub,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductName_Validate,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductName_GetImplementationValue,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductName_SetImplementationValue,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductName_OnValueChanged);
                private static void _ProductName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductName, sf);
                }
                private static bool _ProductName_ComputeIsReadOnly(global::LightSwitchApplication.Product_Sales_for_1997Item e)
                {
                    bool result = false;
                    e.ProductName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductName_Validate(global::LightSwitchApplication.Product_Sales_for_1997Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductName_Validate(r);
                }
                private static string _ProductName_GetImplementationValue(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductName;
                }
                private static void _ProductName_SetImplementationValue(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProductName = v;
                }
                private static void _ProductName_OnValueChanged(global::LightSwitchApplication.Product_Sales_for_1997Item e)
                {
                    e.ProductName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::System.Nullable<decimal>>.Entry
                    ProductSales = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "ProductSales",
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductSales_Stub,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductSales_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductSales_Validate,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductSales_GetImplementationValue,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductSales_SetImplementationValue,
                        global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass.PropertySetProperties._ProductSales_OnValueChanged);
                private static void _ProductSales_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductSales, sf);
                }
                private static bool _ProductSales_ComputeIsReadOnly(global::LightSwitchApplication.Product_Sales_for_1997Item e)
                {
                    bool result = false;
                    e.ProductSales_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductSales_Validate(global::LightSwitchApplication.Product_Sales_for_1997Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductSales_Validate(r);
                }
                private static global::System.Nullable<decimal> _ProductSales_GetImplementationValue(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductSales;
                }
                private static void _ProductSales_SetImplementationValue(global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.ProductSales = v;
                }
                private static void _ProductSales_OnValueChanged(global::LightSwitchApplication.Product_Sales_for_1997Item e)
                {
                    e.ProductSales_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Data _CategoryName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, string>.Data _ProductName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product_Sales_for_1997Item, global::LightSwitchApplication.Product_Sales_for_1997Item.DetailsClass, global::System.Nullable<decimal>>.Data _ProductSales;
            
        }
    
        #endregion
    }
    
    #endregion
}
